hitobito/hitobito_pbs

- app/controllers/population_controller.rb
- app/domain/member_counter.rb
- app/helpers/population_helper.rb
- app/views/population/_birthyears_overview.html.haml
- app/views/population/index.html.haml
- config/locales/views.pbs.de.yml
- config/locales/views.pbs.fr.yml
- config/locales/views.pbs.it.yml
- spec/controllers/population_controller_spec.rb
- spec/domain/member_counter_spec.rb
- spec/helpers/population_helper_spec.rb
- spec/regressions/population_controller_spec.rb
Hallo miteinander! Erst mal, dieser Pull Request ist noch nicht merge-Reif, ich will das hier nur als Diskussionsgrundlage benutzen.
Als AL vermisse ich in der Datenbank die Möglichkeit, schnell einen Überblick über die Jahrgänge meiner Teilnehmer zu sehen, um zu sehen, wo es Löcher gibt etc.
Ich habe mal eine schnell-Version davon implementiert. Wäre es möglich, diesen Change zu integrieren? Wer muss dazu die Zustimmung geben? Falls es möglich wäre, würde ich noch refactoren, Tests hinzufügen etc.
> add age overview for abteilung, crude version

- app/domain/pbs/export/csv/people/people_full.rb
Die PBS führt mehrmals jährlich einen Versand an alle ihre Mitglieder durch. 
Dabei kommen jeweils mehrere Hundert Briefe wegen falscher Adressangaben zurück. Um die fehlerhaften Adressdaten einfacher an die jeweiligen Adressverantwortlichen zu melden, wird die ID der betroffenen Person sowie der Primärgruppe benötigt. So lassen sich die zurück gemeldeten Adressen nach Primärgruppe bündeln und an die öffentliche Kontaktadresse der Gruppe schicken. 
bezieht sich auf: 
https://github.com/hitobito/hitobito/issues/78
> Personen-ID und Primärgruppen-ID exportieren

- config/locales/models.pbs.de.yml
überschreiben vom übernamne durch Pfadinamen in Etikketenlabelview
fixes concerns https://github.com/hitobito/hitobito/issues/77#issuecomment-286471424
> übername durch Pfadiname ersetzen

- app/views/groups/_actions_show_pbs.html.haml
- config/locales/views.pbs.de.yml
It's now too easy to accidentally start a crisis.  This PR adds a confirmation dialog:
> Add confirm to crisis button

- app/views/event/attendances/_list.html.haml
- config/locales/views.pbs.de.yml
Bei einem existierenden Kurs werden im Tab «Anwesenheit» die gespeicherten Werte für jede teilnehmende Person angezeigt und können verändert werden. Wenn jedoch noch kein Wert für eine Person gespeichert wird und ein «BSV-Tage»-Wert auf dem Kurs hinterlegt ist, wird dieser in das Textfeld geschrieben. Dies führt zu der Situation, dass nicht klar ist, ob dieser Wert gespeichert ist oder nicht – und man aus Erfahrung wissen muss, dass diese Seite einfach mal abgesendet werden muss, damit die Werte sicher gespeichert sind. 
Um diesen Ablauf zu verbessern, fügt dieser PR neben dem Feld ein Hinweis «Noch nicht gespeichert» ein, falls der Wert der Standardwert ist und noch nicht gespeichert wurde.
> Kurse: Ungesicherte Werte in der «Anwesenheits»-Ansicht kennzeichnen

- app/models/event/camp.rb
- app/views/events/_fields_pbs.html.haml
- config/locales/models.pbs.de.yml
- config/locales/views.pbs.de.yml
- db/migrate/20191002124400_add_hierarchies_to_camps.rb
- db/migrate/20191002124400_add_hierarchies_to_campy_events.rb
- spec/fixtures/event/dates.yml
- spec/fixtures/events.yml
- spec/models/event/camp_spec.rb
Ich habe die Lagerhierarchien vorerst ohne nested set implementiert. Ich habe damit auch noch keine Annahmen über die Anzahl der Hierarchieebenen im Code festgehalten. Für eine Ebene (Sammellager + Unterlager) ist es so komplett ausreichend. Auch, um erstmal das restliche Interface anzulegen. 
Sobald mehrere Ebene unterstützt werden sollen, sollten wir den Rest der nested_set-Methoden hinzufügen. Genauso fehlt vielleicht noch einen Methode, die ein Lager explizit als Sammellager oder Unterlager kennzeichnet (`super_camp?` und `sub_camp?`). Dies ist bisher nur über das Vorhandensein einer entsprechenden Relation zu erkennen.
Ich wollte hiermit aber mal einen Start machen und bitte um ein Review.
See hitobito/hitobito#830
> Lagerhierachien: Lager als übergeordnetes Lager kennzeichnen

- app/assets/stylesheets/hitobito/customizable/_wagon.scss
- app/controllers/supercamps_controller.rb
- app/helpers/pbs/sheet/event.rb
- app/models/event/camp.rb
- app/views/events/_attrs_primary.html.haml
- config/locales/models.pbs.de.yml
- config/locales/views.pbs.de.yml
- db/migrate/20191021173800_upgrade_camps_to_nested_set.rb
- lib/hitobito_pbs/wagon.rb
Für das Tab "Untergeordnete Lager" habe ich die reine `parent_id`-Lösung zu einem echten nested_set ausgebaut. Bisher wird nur das Tab angezeigt, es ist noch keine Funktion dahinter. Ich bin erst davon ausgegangen, dass ich schon für dieses Issue das nested_set brauche, tatsächlich ist es aber erst im nächsten notwendig.
In der Darstellung werden das übergeordnete Lager oder die direkten Unterlager verlinkt angezeigt.
See hitobito/hitobito#831
> Übergeordnetes Lager anzeigen

- app/controllers/pbs/events_controller.rb
- app/controllers/supercamps_controller.rb
- app/decorators/pbs/group_decorator.rb
- app/helpers/pbs/contact_attrs/control_builder.rb
- app/models/event/camp.rb
- app/views/event/questions/_fields_subcamp.html.haml
- app/views/supercamps/_available.html.haml
- app/views/supercamps/_selectable_supercamps.html.haml
- app/views/supercamps/available.js.haml
- app/views/supercamps/query.js.haml
- config/locales/models.pbs.de.yml
- config/locales/views.pbs.de.yml
- config/routes.rb
- db/migrate/20191021155100_add_subcamp_field_to_questions.rb
- db/migrate/20191028135000_add_contact_attrs_passed_on_to_supercamp_to_events.rb
- spec/controllers/events_controller_spec.rb
- spec/controllers/supercamps_controller_spec.rb
- spec/fabricators/event/question_fabricator.rb
- spec/fixtures/event/dates.yml
- spec/fixtures/events.yml
- spec/models/event/camp_spec.rb
**Depends on https://github.com/hitobito/hitobito/pull/861**
I also merged the commits of #120 into this preemptively, so there shouldn't be any merge conflicts once that one is merged.
Fixes hitobito/hitobito#835, fixes hitobito/hitobito#836
> Lagerhierarchien: Anmeldeangaben und Kontaktdaten auf untergeordnetem Lager

- app/abilities/pbs/event_ability.rb
- app/controllers/subcamps_controller.rb
- app/helpers/filter_navigation/camps.rb
- app/helpers/pbs/sheet/event.rb
- app/helpers/sheet/subcamp.rb
- app/views/subcamps/_list.html.haml
- app/views/subcamps/index.html.haml
- config/locales/views.pbs.de.yml
- config/routes.rb
- spec/abilities/event_ability_spec.rb
- spec/controllers/events_controller_spec.rb
- spec/controllers/subcamps_controller_spec.rb
- spec/fixtures/events.yml
Für die untergeordneten Lager gibt es jetzt eine Liste, die gefiltert werden kann. Sofern man auf einem übergeordneten Lager im Leitungsteam ist, hat man die Berechtigung, die Details und auch die Teilnehmer der untergeordneten Lager anzusehen.
Fixes hitobito/hitobito#832
> Lagerhierarchien: Tab "untergeordnete Lager"

- config/locales/models.pbs.fr.yml
Die französische Bezeichnung "comité des parents" wurde im PBS-Wording durch "conseil des parents" abgelöst. Bin nicht sicher, ob ich die Änderung im richtigen File und an der richtigen Stelle vorgeschlagen habe.
> Topic wording elternrat: Adapt French name for 'Elternrat' from 'comité des parents' to 'conseil des parents', according to current wording.

- app/controllers/pbs/roles_controller.rb
- spec/controllers/event/approvals_controller_spec.rb
```model_params[:deleted_at]``` is always sent in the form, though with a ```''``` value. This leads  to wrong behaviour when creating roles.
> Fix bug in return path

- app/models/group/bundes_kommission.rb
- db/migrate/20190921151245_migrate_bundes_kommission_roles.rb
change permissions for `bundes_kommission`:
- Leitung :layer_read, :group_and_below_full
- Mitglied :layer_read
and migrate existing Roles to the new ` Group::BundesKommission::...`
> change permission for bundes_kommission

- config/settings.yml
Mit der URL scouts.ch können wir die DNS-Einträge jederzeit selber ändern (z.B. wenn wir mal auf einen anderen Server zügeln). Ausserdem hat die Domain etwas mehr Bezug zur Pfadi ;)
> Angepasste URL für das Export-Tool

- app/serializers/pbs/event_serializer.rb
- spec/fixtures/event/participations.yml
- spec/fixtures/event/roles.yml
- spec/serializers/pbs/event_serializer_spec.rb
Mit dem letzten [Commit auf dem PBS EventSerializer](https://github.com/hitobito/hitobito_pbs/commit/a12aa074d92a2c32561bdd6bc4f4278be5da3159#diff-fdff37addd8af470d6ee4602843f83db) ist ein Fehler entstanden, worauf die verlinkten Personen nicht mehr serialisiert wurden.
Das Problem ist entstanden, weil die Methode ```used_attributes``` auf dem Application Decorator  Argumente braucht und den Array bereits filtert: https://github.com/hitobito/hitobito/blob/d615ffff9bde1cc390604b2f8a3eb2a1c8f7499f/app/decorators/application_decorator.rb#L21-L23
Allenfalls wäre es schön, die Methode im ApplicationDecorator zu refactoren mit dem ```&``` und sicherstellen, dass die Methode nicht ohne Argument aufgerufen werden kann (gibt im Moment einfach einen leeren Array zurück).
Bitte möglichst schnell …
> Make entities visible again

- app/models/event/camp.rb
- app/models/event/campy.rb
- spec/models/event/campy_course_spec.rb
This fixes a bug that caused campy courses in which the expected participants are filled in to raise an exception.
https://help.puzzle.ch/#ticket/zoom/1149
> Move calculated fields to Campy

- app/assets/stylesheets/hitobito/customizable/_wagon.scss
Bisher war die Schattenfarbe grün (hitobito-grün anstatt PBS-grün!), hiermit wird sie auf ein zurückhaltenderes Schwarz geändert 😅
> Schatten-Farbe der Sheets ändern zu neutralem transparentem Schwarz

- app/controllers/pbs/people_controller.rb
- app/controllers/pbs/subscriptions_controller.rb
- app/domain/pbs/export/tabular/people/households_full.rb
- app/domain/pbs/export/tabular/people/participations_households_full.rb
- app/jobs/pbs/export/event_participations_export_job.rb
- app/jobs/pbs/export/people_export_job.rb
- app/jobs/pbs/export/subscriptions_job.rb
- lib/hitobito_pbs/wagon.rb
- spec/domain/export/tabular/people/households_spec.rb
The households export with more detail will only be available through a specific URL. The option in the drop down is not included anymore. This way we don't disturb the UI and still offer a solution for users who need more information in the households export.
Also the group_id is included in the people_controller to match the core query again (after the changes from the performance optimization). 
This will replace https://github.com/hitobito/hitobito_pbs/pull/87
> Advanced households export (without disturbing the UI)

- spec/domain/export/tabular/people/participation_ndbjs_row_spec.rb
- spec/domain/person/black_list_detector_spec.rb
Flick für die Tests, welche durch https://github.com/hitobito/hitobito/pull/922 kaputt gemacht wurden.
**Frage vor dem merge:** Die spec spec/domain/export/tabular/people/participation_ndbjs_row_spec.rb ist praktisch identisch mit ihrem Pendant aus hitobito_youth. Wäre es nicht besser, die redundante spec zu löschen?
> Fix tests broken by phone number validation introduced in hitobito core

- app/models/geolocation.rb
- app/models/group/abteilung.rb
- config/locales/models.pbs.de.yml
- spec/controllers/groups_controller_spec.rb
- spec/fabricators/geolocation_fabricator.rb
- spec/models/geolocation_spec.rb
- spec/models/group_spec.rb
Hackathon 2020.01
Validates the geolocations with the WGS84 decimal degree (DD) standard and makes sure the coordinates entered in the groupfinder fields are in Switzerland (approximated by a box, not exactly mapping the border).
Joint work by @Michael-Schaer and me.
> Validate coordinates in groupfinder fields

- app/serializers/pbs/event_participation_serializer.rb
- lib/hitobito_pbs/wagon.rb
- spec/serializers/pbs/event_participation_serializer_spec.rb
Vorab: @Michael-Schaer und @Team Midata: wie seht ihr diesen PR? Ist das für euch in Ordnung so?
Für das Bundeslager wurde der EventParticipationSerializer bereits um alle ```PUBLIC_ATTRS``` erweitert, um mehr oder weniger dieselben Felder auf der JSON Schnittstelle wie im CSV/Excel export zu haben. Bislang fehlen aber noch die Telefonnummern der angemeldeten Personen in eben diesem JSON.
Ich habe deshalb den ```ParticipationSerializer``` mit allen Telefonnummern einer angemeldeten Person erweitert, die als **"öffentlich"** markiert wurden. Im PBS Wagon deshalb, weil ich nicht weiss ob das für alle Wagons passen könnte.
Rückmeldungen technischer oder inhaltlicher natur sind also herzlich willkommen: @Michael-Schaer @lukaseisenring @carlobeltrame
> Add public phone numbers to ParticipationSerializer

- app/models/group/abteilung.rb
- config/locales/models.pbs.de.yml
Es soll eine neue Rolle «Präsidium Elternrat» auf Abteilungsebene geschaffen werden, die Lese-Berechtigung auf Personen der Abteilung und Anlässe aller Art hat. Die Berechtigung der Rolle kann analog Präsidium APV umgesetzt werden.
Der PR fügt eine neue Rolle `Group::Abteilung::PraesidiumElternrat` mit `:group_read`-Permissions hinzu. Die deutsche Übersetzung ist vorhanden, weitere Übersetzungen nicht.  
* [Issue im Trello «MiData Development»](https://trello.com/c/s1QfDj1R/17-midata-z-21-elternrat-st%C3%A4rken)
* [Diskussion im Trello «Team MiData Features»](https://trello.com/c/4oOqXRja/224-elternrat-und-apv-rollen-und-gruppentypen)
> Elternrat stärken (Z-21)

- app/domain/pbs/export/tabular/events/row.rb
- spec/domain/export/tabular/events/row_spec.rb
Im Event-Export erscheint aktuell in den Feldern «Hauptleitung» die erste Person, welche eine «Leitungs»-Rolle hat.
Dieser PR ändert dieses Verhalten für die PBS und exportiert nun in diesen Feldern die Person, welche als Lagerleitung eingetragen wurde (Tab «Betreuung»).
> Events: «Lagerleitung» als «Hauptleitung» exportieren (Z)

- app/serializers/pbs/mailing_list_serializer.rb
- app/serializers/pbs/mailing_list_subscriber_serializer.rb
Auf Abos und Abonnent*innen soll per API zugegriffen werden können. Dies soll unter anderem ermöglichen, dass weitere Versandmöglichkeiten / externe Mailanbieter integriert werden können.
👉 @diegosteiner 
Dieser PR basiert auf dem [Core-PR #963](https://github.com/hitobito/hitobito/pull/963) und ergänzt die neuen Serializers um PBS-spezifische Felder.
* [Issue im Trello «MiData Development»](https://trello.com/c/6EosZKkI/28-midata-z-30-schnittstellen-erweitern-api-f%C3%BCr-abos-und-abonnentinnen)
* [Diskussion im Trello «Team MiData Features»](https://trello.com/c/h5vyzHc6/107-schnittstellen-erweitern)
* Core-Issue [#242](https://github.com/hitobito/hitobito/issues/242)
> API-Zugriff auf Abos und Abonnent*innen, PBS-spezifische Felder (Z-30)

- app/domain/pbs/export/tabular/events/list.rb
- spec/domain/export/csv/events/list_spec.rb
> Das Krisenteam würde es begrüssen, wenn die Notfallnummer ebenfalls im Lager-Export vorhanden ist.
Dieser PR fügt dem Events-Export das Feld `emergency_phone` hinzu.
* [Issue im Trello «MiData Development»](https://trello.com/c/85YQ3Qsm/46-midata-z-44-notfallnummer-in-der-lagerliste)
> Notfallnummer im Lager-Export (Z-44)

- app/domain/pbs/export/tabular/people/households_full.rb
- app/domain/pbs/export/tabular/people/people_address.rb
- app/models/pbs/person.rb
- app/serializers/pbs/person_serializer.rb
- app/views/people/_details_pbs.html.haml
- app/views/people/_fields_pbs.html.haml
- config/locales/models.pbs.de.yml
- db/migrate/20200623000000_add_correspondence_preference_to_person.rb
- lib/hitobito_pbs/wagon.rb
- spec/domain/export/tabular/people/households_spec.rb
- spec/domain/export/tabular/people/people_address_spec.rb
- spec/domain/export/tabular/people/people_full_spec.rb
- spec/models/person_spec.rb
Für Versände in digitalen und analogen Fassungen soll es Personen möglich sein, ihre «Versandpräferenz» (entweder digital oder print) zu speichern, damit sie gezielt angeschrieben werden können. 
Dieser PR fügt dem Person-Model ein neues Attribut `prefers_digital_correspondence` hinzu:
* standardmässig falsch (= print bevorzugt), muss ausgefüllt werden
* wechseln auf digital validiert die Existenz einer Emailadresse
* wird bei gängigen Exporten eingeschlossen
* [Issue im Trello «MiData Development»](https://trello.com/c/rlxnzcNx/23-midata-z-41-sarasani-digital)
* [Issue im Trello «Team MiData Features»](https://trello.com/c/gMp4HM2X/229-sarasani-digital)
> «Sarasani digital»: Attribut für Versandpräferenz (Z-41)

- app/abilities/pbs/event_ability.rb
- app/models/group/abteilung.rb
- app/models/group/bund.rb
- app/models/group/kantonalverband.rb
- app/models/group/region.rb
- app/models/pbs/event/course.rb
- config/settings.yml
- lib/hitobito_pbs/wagon.rb
- spec/controllers/supercamps_controller_spec.rb
- spec/fixtures/events.yml
- spec/fixtures/groups.yml
- spec/models/event/course_spec.rb
- spec/models/event_spec.rb
- spec/regressions/events_controller_camp_spec.rb
- Anlässe sind nicht mehr global sichtbar
- Kurse dann doch wieder, um das PBS-Kurswesen zu unterstützen
- Einige Rollen bekommen erweiterte Rechte (https://github.com/hitobito/hitobito/issues/1047#issuecomment-791239533)
- Anpassung der EventAbility, um Teilnehmer und Kriseteam zu berechtigen
- Spec-Anpassungen, die vorher auf globaler Sichtbarkeit aufbauten
- Leerzeilen entfernt und neu hinzugefügt
See https://github.com/hitobito/hitobito/issues/1047
> Sichtbarkeit von Anlässen (und so), PBS-Edition

- app/domain/event/approver.rb
- app/models/pbs/event/application.rb
- app/models/pbs/event/course.rb
- spec/domain/event/approver_spec.rb
- spec/models/event/application_spec.rb
Scenario:
1. I create a course and accidentally leave the `requires_approval_abteilung`, `requires_approval_region` etc. flags unchecked.
2. Some participant p1 applies for the course
3. I notice my error, edit the course and activate the flag `requires_approval_abteilung`
4. Some other participant p2 applies for the course
Then, the approval of the Abteilung will be requested normally for p2, but no approval will ever be requested for p1.
This PR fixes this problem, by checking and sending out missing approvals (i.e. creating the approval objects in the database and sending the email), whenever the course's `require_approval_*` flags are changed.
@Michael-Schaer please test this and discuss with the AKom whether this is a useful fix. We had this issue in several of our courses this year.
> Fix: Request course approvals when changing the rules on a course

- config/locales/models.pbs.de.yml
Bei der Warnung für die Lagermeldung sollten alle Felder gleich heissen wie im Formular
Screenshot der Warnung: https://i.ibb.co/Zc6bt2b/warning.png
> Textanpassung Erwartete Anzahl Teilnehmende

- app/controllers/pbs/events_controller.rb
- spec/controllers/events_controller_spec.rb
Allow Abteilungsleitung to see the Camp Submit Validation automatically as well.
See https://github.com/hitobito/hitobito_pbs/pull/220
> Allow Abteilungsleitung to see Camp Submit Validation

- app/controllers/pbs/event/roles_controller.rb
- lib/hitobito_pbs/wagon.rb
- spec/controllers/event/roles_controller_spec.rb
Fixes an oversight from https://github.com/hitobito/hitobito/issues/1956
Fixes https://help.puzzle.ch/#ticket/zoom/5860
The attributes of the event participations and event roles have been assigned in a nonstandard way since 2012. Unfortunately, this means we cannot just extend the available fields in the normal way (by adding to the permitted_attrs). Instead, we have to extend the build_entry method so that it sets the fields.
Extending the permitted_attrs works when only adding completely new people to the event. But when adding another role for a person who already had a participation in the event, the assign_attributes call would completely overwrite the role's participation which has previously been carefully crafted in the build_entry method.
> Fix creating event roles for people who already have one

- app/helpers/pbs/dropdown/people_export.rb
- app/jobs/pbs/export/event_participations_export_job.rb
- config/locales/views.pbs.de.yml
- lib/hitobito_pbs/wagon.rb
Merge together with hitobito/hitobito_youth#26
- Versteckt die NDS-Kurs bzw. NDS-Lager Export-Optionen in Anlässen wo sie klar nicht gültig sind
- Exportiert immer nur die Teilnehmenden bei NDS-Kursen, NDS-Lagern und SLRG-Kursen, egal welche Filter gerade eingestellt sind. Zur Info wurde auch noch die Übersetzung der Dropdown-Optionen angepasst.
> Improve camp and course participant exports

- app/views/help/index.html.haml
- config/locales/views.pbs.de.yml
- config/locales/views.pbs.fr.yml
- config/locales/views.pbs.it.yml
"1x1 MiData for coaches" was archived. This pr removes the link to the document
> Remove link to 1x1 MiData for coaches from the help page

- app/domain/alumni/applicable_groups.rb
- app/domain/alumni/invitation.rb
- app/domain/alumni/invitations.rb
- app/domain/alumni/reminders.rb
- app/jobs/alumni_invitations_job.rb
- app/mailers/alumni_mailer.rb
- app/mailers/alumni_mailer/format_helper.rb
- app/models/group/silverscouts.rb
- app/models/group/silverscouts_region.rb
- config/locales/models.pbs.de.yml
- config/settings.yml
- db/migrate/20230918160847_add_alumni_processing_timestamps_to_role.rb
- db/seeds/custom_contents.rb
- spec/controllers/event/lists_controller_spec.rb
- spec/domain/alumni/applicable_groups_spec.rb
- spec/domain/alumni/invitation_spec.rb
- spec/domain/alumni/invitations_spec.rb
- spec/domain/alumni/reminders_spec.rb
- spec/fabricators/event_fabricator.rb
- spec/jobs/alumni_invitations_job_spec.rb
- spec/mailers/alumni_mailer_spec.rb
- spec/models/group_spec.rb
Fixes: #273 
Blocked by: #278, #279
> Implement alumni invitation/reminder emails

- app/controllers/group_health_controller.rb
- app/models/group/abteilung.rb
- app/models/group/erziehungsberechtigten_gremium.rb
- config/locales/models.pbs.de.yml
- config/locales/models.pbs.fr.yml
- config/locales/models.pbs.it.yml
- db/seeds/development/0_groups.rb
- spec/domain/role/type_list_spec.rb
- spec/models/group_spec.rb
Eine neue Gruppe für die Elternaccounts wie ein interes Gremium erstellt. Rollen:
- Mitglied
- Selbstregistrierte*r
Beide Rollen mit basic_permission_only und ausgenommen vom HealthCheck Export.
> Neue Gruppe für Elternaccounts

- app/models/pbs/event/participation_contact_data.rb
After the conversion to the core-field, the manual addition is not needed anymore.
fixes hitobito/hitobito#2330
> Remove duplicated field

- lib/tasks/geoblocking.rake
This generates a partial config for the geoblocking proxy. 
See #296
The proxy itself is configured elsewhere and activated in https://gitlab.puzzle.ch/pitc_hit/hitobito-configmanagement/-/merge_requests/9
> Allow creating a nginx-config for geoblocking

- app/controllers/group_health_controller.rb
- spec/controllers/group_health_controller_spec.rb
Fixes https://github.com/digio-ch/pbs-healthcheck-core/issues/138
Fixes #400
Fixes #401
Refs #398
Apparently, Postgres does not consistently order rows the same way when using OFFSET vs. when not using OFFSET:
```sql
SELECT 20146 in (SELECT DISTINCT "people"."id" FROM "people" INNER JOIN [...] WHERE [...]
LIMIT 20000);
=> true
```
```sql
SELECT 20146 in (SELECT DISTINCT "people"."id" FROM "people" INNER JOIN [...] WHERE [...]
LIMIT 10000);
=> false
```
```sql
SELECT 20146 in (SELECT DISTINCT "people"."id" FROM "people" INNER JOIN [...] WHERE [...]
LIMIT 10000 OFFSET 10000);
=> false
```
The fix is to use an ORDER BY statement when using LIMIT and OFFSET:
```sql
SELECT 20146 in (SELECT DISTINCT "people"."id" FROM "people" INNER JOIN [...] WHERE [...]
ORDER BY id
LIMIT 10000 OFFSET 10000); …
```
> Fix group_health API bugs

- db/migrate/20250625120000_fix_broken_events.rb
Refs hitobito/hitobito#3475
Fixes events left broken in the correspondence_language migration (451b4c9c265dfcfb74ed58989275455c45c9a58d)
Fixes events left broken in the structured address migration hitobito/hitobito#2595 hitobito/hitobito#2682
Fixes events left broken when adding the ahv_number question hitobito/hitobito_youth#101
After this migration, there are more invalid events, most of them broken by the added validation from #1882, but these are cleanable by the users themselves.
The same migration minus the supercamp attribute needs to be applied to the youth wagon as well: hitobito/hitobito_youth#119
Tested locally with a PBS prod dump.
> Fix broken events
