- CHANGELOG.md
- app/models/group/abteilung.rb
- config/locales/models.pbs.de.yml
> Rolle Materialwart und Heimverwalter aktiviert

- CHANGELOG.md
- app/controllers/pbs/event/lists_controller.rb
- app/domain/export/tabular/events/advanced_bsv_list.rb
- app/domain/pbs/export/tabular/events/bsv_row.rb
- app/views/event/lists/_buttons_pbs.html.haml
- config/locales/views.pbs.de.yml
- spec/controllers/event/lists_controller_spec.rb
> Advanced BSV/LKB Export

- app/abilities/pbs/various_ability.rb
- app/controllers/black_lists_controller.rb
- app/domain/person/black_list_detector.rb
- app/helpers/sheet/black_list.rb
- app/mailers/black_list_mailer.rb
- app/models/black_list.rb
- app/models/pbs/event/participation.rb
- app/models/pbs/person.rb
- app/models/pbs/role.rb
- app/views/black_lists/_list.html.haml
- app/views/shared/_admin_nav_kinds_pbs.html.haml
- config/locales/models.pbs.de.yml
- config/locales/views.pbs.de.yml
- config/routes.rb
- db/migrate/20181214104246_create_black_lists.rb
- db/seeds/custom_contents.rb
- lib/hitobito_pbs/wagon.rb
- spec/abilities/black_list_spec.rb
- spec/controllers/black_lists_controller_spec.rb
- spec/domain/person/black_list_detector_spec.rb
- spec/fabricators/black_list_fabricator.rb
- spec/fixtures/black_lists.yml
- spec/mailers/black_list_mailer_spec.rb
- spec/models/black_list_spec.rb
- spec/models/event/participation_spec.rb
- spec/models/role_spec.rb
https://ticket.puzzle.ch/projects/pbsc-vbl/work_packages/44713/activity
> Caterpillars were buried
> Implemented 44713

- app/domain/export/tabular/events/advanced_bsv_list.rb
- app/domain/pbs/export/tabular/events/bsv_row.rb
- spec/controllers/event/lists_controller_spec.rb
- spec/domain/export/tabular/events/bsv_row_spec.rb
should fix hitobito/hitobito#670
> adds missing rows and attendance summary

- config/settings.yml
Nachdem https://github.com/hitobito/hitobito/pull/693 gemerged wurde: Übersetzt die Links im Footer und fügt das PDF zur Datennutzung hinzu.
@Michael-Schaer : Bitte absegnen
> Translate footer links

- app/assets/javascripts/wagon.js.coffee
- app/assets/stylesheets/hitobito/customizable/_wagon.scss
- app/controllers/pbs/events_controller.rb
- app/controllers/supercamps_controller.rb
- app/decorators/pbs/group_decorator.rb
- app/helpers/events_pbs_helper.rb
- app/models/event/camp.rb
- app/views/events/_fields_pbs.html.haml
- app/views/supercamps/_available.html.haml
- app/views/supercamps/_selectable_supercamps.html.haml
- app/views/supercamps/available.js.haml
- app/views/supercamps/query.js.haml
- config/locales/views.pbs.de.yml
- config/routes.rb
- lib/hitobito_pbs/wagon.rb
- spec/controllers/events_controller_spec.rb
- spec/controllers/supercamps_controller_spec.rb
- spec/fixtures/event/dates.yml
- spec/fixtures/events.yml
- spec/models/event/camp_spec.rb
> Lagerhierarchien: Untergeordnetes Lager erstellen

- app/controllers/pbs/event/participations_controller.rb
- app/controllers/pbs/event/qualifications_controller.rb
- app/decorators/pbs/event/participation_decorator.rb
- app/decorators/pbs/event_decorator.rb
- app/helpers/events_pbs_helper.rb
- app/mailers/event/course/confirmation_mailer.rb
- app/models/pbs/event/course.rb
- app/models/pbs/event/kind.rb
- app/views/event/kinds/_fields_pbs.html.haml
- app/views/event/participations/_actions_show_pbs.html.haml
- app/views/event/qualifications/index.html.haml
- config/locales/models.pbs.de.yml
- config/locales/views.pbs.de.yml
- config/routes.rb
- config/settings.yml
- db/migrate/20190917120958_add_course_confirmation_attrs.rb
- db/seeds/custom_contents.rb
- lib/hitobito_pbs/wagon.rb
- spec/controllers/event/qualifications_controller_spec.rb
- spec/decorator/event/participation_decorator_spec.rb
- spec/decorator/event_decorator_spec.rb
- spec/fabricators/event/kind_fabricator.rb
- spec/mailers/event/course/confirmation_mailer_spec.rb
- spec/models/event/kind_spec.rb
- spec/views/event/participations/_actions_show.html.haml_spec.rb
- spec/views/event/qualifications/index.html.haml_spec.rb
Fixes hitobito/hitobito#741
Implementation basically complete. To do:
> Course confirmations

- app/views/event/questions/_fields_subcamp.html.haml
Fixes hitobito_pbs/spec/regressions/events_controller_spec.rb, and editing courses
Refs hitobito/hitobito#835
> Fix regression spec that was broken for courses

- app/controllers/pbs/event/participations_controller.rb
- spec/controllers/event/participations_controller_spec.rb
Bug caused participation display of other event kinds to fail.
Refs hitobito/hitobito#741
> Fix side-effect of course confirmation url

- app/serializers/pbs/event_serializer.rb
- lib/hitobito_pbs/wagon.rb
Extends the JSON API for camps and courses by additional attributes.
> Extend Events JSON API

- app/serializers/pbs/event_serializer.rb
Followup to hitobito/hitobito_pbs#109
> Add abteilungsleitung and coach to serialized camp aswell

- app/serializers/pbs/event_serializer.rb
> Add lagerleiter aswell

- config/settings.yml
> Activate translated course confirmations

- app/controllers/supercamps_controller.rb
- app/decorators/pbs/group_decorator.rb
- app/helpers/events_pbs_helper.rb
- app/models/event/camp.rb
- app/models/pbs/event.rb
- app/views/events/_fields_pbs.html.haml
- config/locales/models.pbs.de.yml
- config/locales/views.pbs.de.yml
- spec/controllers/supercamps_controller_spec.rb
- spec/fixtures/event/dates.yml
- spec/fixtures/events.yml
Fixes the remaining remarks in hitobito/hitobito#834 and hitobito/hitobito#848.
> Supercamp fixes

- app/controllers/supercamps_controller.rb
- app/models/event/camp.rb
- app/views/supercamps/_available.html.haml
> Prevent supercamp loops

- app/views/events/_actions_show_pbs.html.haml
- lib/hitobito_pbs/wagon.rb
See hitobito/hitobito#826.
Includes a fix for hitobito/hitobito_pbs#101
> Migrate FontAwesome to version 5, and add icon for Menüpunkt Lager

- app/assets/stylesheets/hitobito/customizable/_variables.scss
- config/settings.yml
In Zusammenhang mit hitobito/hitobito#842.
> Hintergrundfarbe abhängig von Umgebung

- app/models/event/camp.rb
- spec/models/event/camp_spec.rb
> Fix camp confirmed info

- app/views/groups/_fields_pbs.html.haml
- config/locales/views.pbs.de.yml
- config/locales/views.pbs.fr.yml
- config/locales/views.pbs.it.yml
Fügt im Formular für Gruppen ein Hilfetext beim Feld «HealthCheck» / group_health hinzu.
> Added help text for group's group_health field

- config/locales/models.pbs.de.yml
- config/locales/models.pbs.fr.yml
- config/locales/views.pbs.de.yml
- config/locales/views.pbs.fr.yml
- spec/controllers/event/participations_controller_spec.rb
- spec/controllers/roles_controller_spec.rb
- spec/domain/export/tabular/people/people_address_spec.rb
- spec/mailers/event/course/confirmation_mailer_spec.rb
- spec/mailers/event/participation_mailer_spec.rb
- spec/mailers/person/add_request_mailer_spec.rb
- spec/mailers/person/login_mailer_spec.rb
- spec/models/person_spec.rb
- spec/models/salutation_spec.rb
- spec/regressions/events_controller_camp_spec.rb
Eine erste Version für die Genderneutralen Sprache, besonders der Rollen-Bezeichnungen.
Bitte mergen und auf das Testsystem ausrollen, damit wir das überprüfen können. Falls der Revert stört, kann ich das auch noch mal neu machen ;)
> Genderneutralesprache

- db/migrate/20200706153000_prolong_j_s_qualifications.rb
- db/seeds/development/event_kinds.rb
> Prolong certain J+S qualifications due to COVID-19

- config/locales/views.pbs.de.yml
Text angepasst für produktive Version des HealthChecks
> Text Opt-in HealthCheck

- app/domain/export/pdf/camp_application/leaders_section.rb
> Replace return with next in leader block

- .github/workflows/tests.yml
> CI: Add GitHub action

- config/locales/views.pbs.de.yml
- spec/controllers/event/lists_controller_spec.rb
Merge together with hitobito/hitobito#1352
> Adjust course offerer translation

- app/domain/pbs/export/tabular/people/households_full.rb
- spec/domain/export/tabular/people/households_spec.rb
Replaces #177 in order to trigger Github Actions CI
> Add digital correspondence to household_full export

- app/decorators/pbs/event/participation_decorator.rb
- spec/controllers/event/participations_controller_spec.rb
Fixes https://sentry.puzzle.ch/pitc/hitobito-backend/issues/46275/events/1491168/
> Fix displaying course participations of household members

- CHANGELOG.md
- app/models/pbs/mailing_list.rb
- config/locales/models.pbs.de.yml
- lib/hitobito_pbs/wagon.rb
- spec/fixtures/mailing_lists.yml
- spec/models/mailing_list_spec.rb
Alternative, less intrusive solution for #221
> Validate mail_name suffix when changing mail_name

- app/models/group/abteilung.rb
- app/models/group/bund.rb
- app/models/group/kantonalverband.rb
- app/models/group/region.rb
- config/locales/models.pbs.de.yml
Having finance as separate roles should help giving the rights only to selected people
> Adding finance right for testing purposes. 

- db/migrate/20220809150800_require_group_add_requests_globally.rb
> Activate group-add-requests on all groups

- app/domain/pbs/events/filter/groups.rb
- app/helpers/pbs/events_helper.rb
- lib/hitobito_pbs/wagon.rb
- spec/domain/events/filter/groups_spec.rb
Refs: https://github.com/hitobito/hitobito/issues/1813
> Prevent core changes to course filter from taking effect

- CHANGELOG.md
- lib/hitobito_pbs/wagon.rb
Fixes hitobito/hitobito_pbs#233
> Allow event speakers to be qualified like event leaders

- CHANGELOG.md
- app/abilities/pbs/token_ability.rb
- app/controllers/group_health_controller.rb
- app/models/group/kantonalverband.rb
- app/models/group/region.rb
- app/models/pbs/service_token.rb
- app/views/service_tokens/_fields_pbs.html.haml
- config/locales/models.pbs.de.yml
- config/routes.rb
- db/migrate/20220928113816_add_census_evaluations_to_service_tokens.rb
- lib/hitobito_pbs/wagon.rb
- spec/controllers/group_health_controller_spec.rb
- spec/domain/event/approver_spec.rb
- spec/fixtures/event/participations.yml
- spec/fixtures/events.yml
- spec/fixtures/people.yml
- spec/fixtures/roles.yml
- spec/jobs/event/approval_request_job_spec.rb
> Adjust and expand group health

- app/decorators/pbs/person_decorator.rb
Goes with https://github.com/hitobito/hitobito/pull/1399
> Use current_oauth_token helper in person decorator

- app/models/pbs/event/course.rb
Refs: https://github.com/hitobito/hitobito/issues/1927
> Customize supports_applications for course

- app/models/pbs/event/course.rb
This reverts commit 81d5a8305e8e93683ea6a1ad146762da4de7e565.
Refs: https://github.com/hitobito/hitobito/issues/1950
Merge first: https://github.com/hitobito/hitobito/pull/1951
> Revert "Customize supports_applications for course"

- config/settings.yml
Vielleicht die einfachste Lösung für https://github.com/hitobito/hitobito/issues/1960?
> Switching to CSV encoding UTF-8, up for discussion

- app/domain/pbs/person/add_request/approver/event.rb
- app/models/pbs/event.rb
- app/models/pbs/event/participation.rb
- lib/hitobito_pbs/wagon.rb
- spec/domain/person/add_request/approver/event_spec.rb
> Fix event request approval for j+s events, fixes #253

- app/controllers/event/attendances_controller.rb
- app/decorators/pbs/event_decorator.rb
- app/helpers/events_pbs_helper.rb
- app/helpers/pbs/sheet/event.rb
- app/views/event/attendances/_list.html.haml
for closed or completed events
See also: https://trello.com/c/Ay9dukU0
> add exclamation mark to attendances if there are unsaved bsv days 

- app/controllers/pbs/group/person_add_requests_controller.rb
- app/models/pbs/group.rb
- app/views/group/person_add_requests/index.html.haml
- lib/hitobito_pbs/wagon.rb
- spec/controllers/group/person_add_requests_controller_spec.rb
> Always require person add requests

- app/controllers/group_health_controller.rb
- spec/controllers/group_health_controller_spec.rb
> Adjust group health census evaluation structure

- app/models/group/bund.rb
- app/models/group/kantonalverband.rb
- app/models/group/region.rb
- config/locales/models.pbs.de.yml
- config/locales/models.pbs.fr.yml
- config/locales/models.pbs.it.yml
Mehr Infos: https://trello.com/c/25R4bx5q/377-rolle-verantwortlicher-ehrenamtlichen-management
> New Role for managing the volunteers

- README.md
- app/models/group/abteilung.rb
- app/models/group/ehemalige.rb
- app/models/group/kantonalverband.rb
- app/models/group/region.rb
- config/locales/models.pbs.de.yml
- spec/domain/role/type_list_spec.rb
- spec/models/group_spec.rb
Closes #270 
DO NOT MERGE YET
We'll wait until everything regarding SiSc is ready or actively being worked on. Otherwise we will be blocking releases
> Add new ehemalige group

- config/settings.yml
Refs: https://github.com/hitobito/hitobito/issues/2259
> Disable self service managed creation

- CHANGELOG.md
- app/domain/pbs/people/minimizer.rb
- lib/hitobito_pbs/wagon.rb
- spec/domain/people/minimizer_spec.rb
> Minimize person data

- config/settings.yml
- db/migrate/20231215154134_set_block_warning_sent_at_for_people.rb
Gehört zu [hitobito#2069](https://github.com/hitobito/hitobito/issues/2069) und ist abhängig von [hitobito#2291](https://github.com/hitobito/hitobito/pull/2291/files#diff-279ca9ae507ec4db5057fde12d7fdc00c92959532b9eaec21df854ca90fcbce9)
> Feature: enable inactivity block for wagon

- lib/hitobito_pbs/wagon.rb
> Add recurring wagon jobs to JobManager

- app/views/census_evaluation/abteilung/_totals.html.haml
- app/views/census_evaluation/base/index.html.haml
- app/views/event/attendances/index.html.haml
fixes: [#2477](https://github.com/hitobito/hitobito/issues/2477)
> fix reported ui issues

- app/controllers/event/approvals_controller.rb
- app/controllers/member_counts_controller.rb
> Add missing unprocessable_entity status codes

- app/controllers/pbs/event/participations_controller.rb
- db/migrate/20240425130134_set_automatic_assignment_for_pbs_courses.rb
> Set automatic assignment for courses

- CHANGELOG.md
- app/jobs/event/approval_cleanup_job.rb
- lib/hitobito_pbs/wagon.rb
- spec/jobs/event/approval_cleanup_job_spec.rb
- spec/jobs/job_manager_spec.rb
> Cleanup approval-text after the course has ended

- app/domain/pbs/people/minimizer.rb
- spec/controllers/event/lists_controller_spec.rb
- spec/domain/people/minimizer_spec.rb
- spec/spec_helper.rb
> Adapt to changed columns

- config/settings.yml
See https://github.com/hitobito/hitobito/issues/2106#issuecomment-1589666528
Vor dem Release soll das deaktiviert werden oder auf einen vernünftigen Wert gesetzt werden.
> Enable cleanup and set to shortest possible duration for tests

- CHANGELOG.md
- db/seeds/custom_contents.rb
> rename custom contents

- app/views/contactable/_address_fields_pbs.html.haml
- app/views/person/households/_custom_fields_pbs.html.haml
- spec/views/people/_fields.html.haml_spec.rb
> Reintroduce prefers_digital_correspondence field to person and add spec

- app/mailers/group_membership_mailer.rb
> improve mailer

- app/domain/alumni/invitations.rb
- app/domain/alumni/reminders.rb
- app/domain/event/approver.rb
- app/domain/member_counter.rb
- app/models/pbs/role.rb
- db/migrate/20230918160847_add_alumni_processing_timestamps_to_role.rb
- db/seeds/development/events.rb
- lib/tasks/people.rake
- spec/controllers/population_controller_spec.rb
- spec/controllers/roles_controller_spec.rb
- spec/domain/alumni/invitation_spec.rb
- spec/domain/alumni/invitations_spec.rb
- spec/domain/alumni/reminders_spec.rb
- spec/domain/person/family_member_finder_spec.rb
- spec/models/role_spec.rb
- spec/support/graphiti/schema.json
> Add explicit #start_on/#end_on to Role, remove FutureRole, Role#delete_on

- spec/controllers/event/attendances_controller_spec.rb
Requires: https://github.com/hitobito/hitobito/pull/3028
Refs: https://help.puzzle.ch/#ticket/zoom/8532
CI run: https://github.com/hitobito/hitobito_pbs/actions/runs/12027206992
> Add spec to ensure correct attendance bsv days

- app/controllers/group_health_controller.rb
https://sentry.puzzle.ch/pitc/hitobito-backend/issues/73549/
> Replace with_deleted with with_inactive

- app/models/pbs/event/date.rb
- lib/hitobito_pbs/wagon.rb
- spec/decorator/event/participation_decorator_spec.rb
Resolves https://help.puzzle.ch/#ticket/zoom/8643
> Restore earlier default rendering of date-durations

- app/jobs/alumni_invitations_job.rb
- app/views/events/_actions_show_pbs.html.haml
Relates to https://github.com/hitobito/hitobito/pull/3151
> Fix recurring job

- lib/hitobito_pbs/wagon.rb
Fixes #343
See https://github.com/hitobito/hitobito/pull/3162
> Add all applicable course-leaders for API

- app/decorators/pbs/person_decorator.rb
- app/views/people/_details_pbs.html.haml
- spec/decorator/person_decorator_spec.rb
> We want to link unique people, not their roles
